// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hasicskyutok.Models;

#nullable disable

namespace hasickyutok.Migrations
{
    [DbContext(typeof(hasicskyutokDbContext))]
    [Migration("20220824123828_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");
#pragma warning restore 612, 618
        }
    }
}
