// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hasicskyutok.Models;

#nullable disable

namespace hasickyutok.Migrations
{
    [DbContext(typeof(hasicskyutokDbContext))]
    [Migration("20220824124934_Aktualizace")]
    partial class Aktualizace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("hasicskyutok.Models.Druzstvo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategorieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartovniCislo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("KategorieID");

                    b.ToTable("Druzstva");
                });

            modelBuilder.Entity("hasicskyutok.Models.Kategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nazev")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("hasicskyutok.Models.Druzstvo", b =>
                {
                    b.HasOne("hasicskyutok.Models.Kategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });
#pragma warning restore 612, 618
        }
    }
}
